sudo: required
dist: xenial
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-science texlive-generic-extra texlive-bibtex-extra biber pdf2svg imagemagick
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create --yes -n phd_thesis python=3.6
  - source activate phd_thesis
  - conda install --yes pandoc pandoc-crossref panflute lxml cssselect python-slugify
script:
  - make pdf
  - make html
  - mv thesis.pdf html_output/.
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html_output
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer_from_gh: true
  on:
    branch: master